### ISSUE TITLE
Allow Users to Customize IOT API Server URL

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/pan.dev#230]
## Documentation link

Location: https://pan.dev/iot/api/alert-list/

## Describe the problem

Server URL doesn't resolve since it includes a variable/placeholder: `https://{customer-name}.iot.paloaltonetworks.com`

## Suggested fix

Provide a way for users to enter the value for `{customer-name}`. One solution would be to use the OpenAPI plugins ability to define variables for parts of the server URL:

```
servers:
  - url: https://{customer_name}.iot.paloaltonetworks.com
    variables:
      customer_name:
        default: "customer_name"
```

> Please note that `-` is not allowed in variable names, which is why an `_` is used in the example above.

Example usage:

https://user-images.githubusercontent.com/9343811/210891508-37a10648-a225-49c3-8171-7fe805ff6ee0.mov
